### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by quuhua911** [hzli-ucas/CCF-OCR#1]
(chineseocr) quh@quh-Z370P-D3:~/pythonwork/tr/CCF-OCR$ python main.py
read Chinese alphabet from file
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import recognition
  File "/home/quh/pythonwork/tr/CCF-OCR/recognition.py", line 14, in <module>
    alphabet = f.read().replace('\n', '')
  File "/home/quh/.conda/envs/chineseocr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 23: invalid start byte

**Comment by hzli-ucas** [comment]
你试试把`recognition.py`文件的第13行，`open('data/chs_alphabet.txt','r')`替换成`open('data/chs_alphabet.txt','r',encoding='ANSI')`。

**Comment by quuhua911** [comment]
问题解决了．是编码差异，这样处理一下就可以解决了．sudo iconv -f 'gbk' -t 'utf-8' chs_alphabet.txt > chs_alphabet1.txt
