### ISSUE TITLE
请问关于水印模板文件的生成能开源吗？

### ISSUE THREAD

**Issue by quuhua911** [hzli-ucas/CCF-OCR#2]
你好，这两个文件的生成能开源吗？或者有没有什么可以指点的地方，比如您参考的是哪个开源算法？
# 水印的Laplace模板用于精确定位
wm_filter = [np.load('data/watermark1_laplace.npy'), np.load('data/watermark2_laplace.npy')]
# 二值图模板用于生成蒙版以进行后续去水印操作
wm_img = [np.load('data/watermark1_solid.npy'), np.load('data/watermark2_solid.npy')]

**Comment by hzli-ucas** [comment]
生成模板用的是最直观的办法，即README中提到的`模板图像是从训练集取相应图像，计算多幅（500-1000）图像的均值得到。`未开源是因为之前整理代码的时候，觉得之后用不着，就删掉了。
以水印为例，具体的做法是，先用图像处理软件裁剪出水印区域、二值化、保存图像，作为初始模板。这个初始模板不需要太精细，主要是用于最初的定位。【其实直接使用该二值图像做模板也没问题，只是可能会有些误差。】一样的模板匹配流程（卷积），根据匹配结果判断水印类型和位置，从匹配图像中裁剪出模板对应的区域，把多幅图像的水印区域求均值得到新的模板图像，最后保存为numpy类型变量。
