### ISSUE TITLE
可以给出详细的运行步骤吗

### ISSUE THREAD

**Issue by upupbo** [hzli-ucas/CCF-OCR#4]

**Comment by hzli-ucas** [comment]
我不太明白“详细的运行步骤”指的是？README的“方案简介”中说了，想要运行程序的话，调用main.py即可。整个过程分为身份证定位、文本行定位、文本识别三个步骤，分别对应了三个函数。你可以在main.py中看到这三个函数的调用顺序，并可以在location_card.py、location_text.py、recognition.py文件中查看函数的详细定义。函数部分有一些注释，再结合README中的“方案简介”，应该是很详细了？
