### ISSUE TITLE
模型不匹配

### ISSUE THREAD

**Issue by Rashomon5487** [hzli-ucas/CCF-OCR#5]
RuntimeError: Error(s) in loading state_dict for chsNet:
        size mismatch for cnn.conv6.weight: copying a param with shape torch.Size([6857, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([6937, 512, 1, 1]).
        size mismatch for cnn.conv6.bias: copying a param with shape torch.Size([6857]) from checkpoint, the shape in current model is torch.Size([6937]).

**Comment by hzli-ucas** [comment]
是不是字符集的问题？当前模型中cnn.conv6.weight的形状，从文件[network.py](https://github.com/hzli-ucas/CCF-OCR/blob/master/networks.py)第84行可知，应该是torch.Size([nclass,512,1,1])。传递进去的nclass参数在[recognition.py](https://github.com/hzli-ucas/CCF-OCR/blob/master/recognition.py)第17行，可以看到是len(alphabet[0])+1。而alphabet[0]的长度是文件[data/chs_alphabet.txt](https://github.com/hzli-ucas/CCF-OCR/blob/master/data/chs_alphabet.txt)中的字符数目，可以看到是6956个。而你这里是读出了6936个字符？是不是修改了chs_alphabet.txt文件，或者读取时默认字符集不对？
