### ISSUE TITLE
您好，可否详细讲下训练模型过程？

### ISSUE THREAD

**Issue by AIShangGao** [hzli-ucas/CCF-OCR#6]
最近在学习OCR识别模型，想复现下实验结果，可否详细讲下使用的训练集及训练过程？谢谢您～

**Comment by hzli-ucas** [comment]
训练集是写了个MFC工程自己生成的，先用二级字库加上竞赛训练集中的生僻字作为字符集，随机抽取字符排成文本行，再加水印、变形、加噪、模糊得到文本图像，用CImage类和opencv实现的。
训练过程就是用[pytorch+CTC](https://github.com/hzli-ucas/warp-ctc)在文本行图像上的端到端。先在自己生成的训练集上训练，模型收敛后，再在竞赛训练集的文本行图像上进行微调（用location_text.py截取文本行）。汉字的类别比较多，为了加速收敛先在单字图像上预训练模型，可以参考下[这篇论文](https://link.springer.com/article/10.1007/s11042-019-7410-1)。具体的训练参数记不清了。
